// Code generated by protoc-gen-go. DO NOT EDIT.
// source: models/stockQuote.proto

package models

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StockQuoteResponse struct {
	Quote                *StockQuote `protobuf:"bytes,1,opt,name=quote,json=Global Quote,proto3" json:"quote,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *StockQuoteResponse) Reset()         { *m = StockQuoteResponse{} }
func (m *StockQuoteResponse) String() string { return proto.CompactTextString(m) }
func (*StockQuoteResponse) ProtoMessage()    {}
func (*StockQuoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec36c2c48b1940b2, []int{0}
}

func (m *StockQuoteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockQuoteResponse.Unmarshal(m, b)
}
func (m *StockQuoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockQuoteResponse.Marshal(b, m, deterministic)
}
func (m *StockQuoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockQuoteResponse.Merge(m, src)
}
func (m *StockQuoteResponse) XXX_Size() int {
	return xxx_messageInfo_StockQuoteResponse.Size(m)
}
func (m *StockQuoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StockQuoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StockQuoteResponse proto.InternalMessageInfo

func (m *StockQuoteResponse) GetQuote() *StockQuote {
	if m != nil {
		return m.Quote
	}
	return nil
}

type StockQuote struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,json=01. symbol,proto3" json:"symbol,omitempty"`
	Open                 string   `protobuf:"bytes,2,opt,name=open,json=02. open,proto3" json:"open,omitempty"`
	High                 string   `protobuf:"bytes,3,opt,name=high,json=03. high,proto3" json:"high,omitempty"`
	Low                  string   `protobuf:"bytes,4,opt,name=low,json=04. low,proto3" json:"low,omitempty"`
	Price                string   `protobuf:"bytes,5,opt,name=price,json=05. price,proto3" json:"price,omitempty"`
	Volume               string   `protobuf:"bytes,6,opt,name=volume,json=06. volume,proto3" json:"volume,omitempty"`
	LatestTradingDay     string   `protobuf:"bytes,7,opt,name=latestTradingDay,json=07. latest trading day,proto3" json:"latestTradingDay,omitempty"`
	PreviousClose        string   `protobuf:"bytes,8,opt,name=previousClose,json=08. previous close,proto3" json:"previousClose,omitempty"`
	Change               string   `protobuf:"bytes,9,opt,name=change,json=09. change,proto3" json:"change,omitempty"`
	ChangePercent        string   `protobuf:"bytes,10,opt,name=changePercent,json=10. change percent,proto3" json:"changePercent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StockQuote) Reset()         { *m = StockQuote{} }
func (m *StockQuote) String() string { return proto.CompactTextString(m) }
func (*StockQuote) ProtoMessage()    {}
func (*StockQuote) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec36c2c48b1940b2, []int{1}
}

func (m *StockQuote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockQuote.Unmarshal(m, b)
}
func (m *StockQuote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockQuote.Marshal(b, m, deterministic)
}
func (m *StockQuote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockQuote.Merge(m, src)
}
func (m *StockQuote) XXX_Size() int {
	return xxx_messageInfo_StockQuote.Size(m)
}
func (m *StockQuote) XXX_DiscardUnknown() {
	xxx_messageInfo_StockQuote.DiscardUnknown(m)
}

var xxx_messageInfo_StockQuote proto.InternalMessageInfo

func (m *StockQuote) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *StockQuote) GetOpen() string {
	if m != nil {
		return m.Open
	}
	return ""
}

func (m *StockQuote) GetHigh() string {
	if m != nil {
		return m.High
	}
	return ""
}

func (m *StockQuote) GetLow() string {
	if m != nil {
		return m.Low
	}
	return ""
}

func (m *StockQuote) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *StockQuote) GetVolume() string {
	if m != nil {
		return m.Volume
	}
	return ""
}

func (m *StockQuote) GetLatestTradingDay() string {
	if m != nil {
		return m.LatestTradingDay
	}
	return ""
}

func (m *StockQuote) GetPreviousClose() string {
	if m != nil {
		return m.PreviousClose
	}
	return ""
}

func (m *StockQuote) GetChange() string {
	if m != nil {
		return m.Change
	}
	return ""
}

func (m *StockQuote) GetChangePercent() string {
	if m != nil {
		return m.ChangePercent
	}
	return ""
}

func init() {
	proto.RegisterType((*StockQuoteResponse)(nil), "models.StockQuoteResponse")
	proto.RegisterType((*StockQuote)(nil), "models.StockQuote")
}

func init() { proto.RegisterFile("models/stockQuote.proto", fileDescriptor_ec36c2c48b1940b2) }

var fileDescriptor_ec36c2c48b1940b2 = []byte{
	// 306 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0xcb, 0x4e, 0x02, 0x31,
	0x14, 0x86, 0xe5, 0x36, 0xc0, 0x51, 0x13, 0xd3, 0x18, 0x6c, 0x5c, 0x9d, 0xb0, 0xd2, 0x4d, 0x29,
	0xe0, 0x75, 0xeb, 0x25, 0x6e, 0x15, 0x7d, 0x81, 0x61, 0x38, 0x81, 0x89, 0x65, 0xce, 0x38, 0x2d,
	0x10, 0x5e, 0xcd, 0x27, 0xf0, 0xb1, 0x4c, 0x5b, 0xbc, 0xec, 0x7a, 0xbe, 0xef, 0xcf, 0xff, 0x2f,
	0x0a, 0x27, 0x4b, 0x9e, 0x91, 0xb1, 0x03, 0xeb, 0x38, 0x7b, 0x7f, 0x59, 0xb1, 0x23, 0x55, 0x56,
	0xec, 0x58, 0x24, 0x51, 0xf4, 0x1f, 0x41, 0xbc, 0xfe, 0xba, 0x09, 0xd9, 0x92, 0x0b, 0x4b, 0x62,
	0x00, 0xad, 0x0f, 0x0f, 0x64, 0x0d, 0x6b, 0x67, 0xfb, 0x23, 0xa1, 0x62, 0x5a, 0xfd, 0x8b, 0x1e,
	0x3c, 0x19, 0x9e, 0xa6, 0x06, 0xc3, 0xd5, 0xff, 0xaa, 0x03, 0xfc, 0x49, 0x71, 0x0a, 0x89, 0xdd,
	0x2e, 0xa7, 0x6c, 0x42, 0x41, 0x77, 0x02, 0x7a, 0xa8, 0x30, 0x12, 0xd1, 0x83, 0x26, 0x97, 0x54,
	0xc8, 0x7a, 0x30, 0x1d, 0x3d, 0x52, 0xe8, 0x6f, 0xcf, 0x17, 0xf9, 0x7c, 0x21, 0x1b, 0x3b, 0x3e,
	0x56, 0xe8, 0x6f, 0x71, 0x0c, 0x0d, 0xc3, 0x1b, 0xd9, 0x0c, 0xb8, 0xad, 0x2f, 0x14, 0x1a, 0xde,
	0x08, 0x09, 0xad, 0xb2, 0xca, 0x33, 0x92, 0xad, 0xc0, 0xbb, 0xfa, 0x52, 0x61, 0x00, 0x7e, 0x7b,
	0xcd, 0x66, 0xb5, 0x24, 0x99, 0xec, 0xb6, 0xaf, 0x14, 0x46, 0x22, 0x34, 0x1c, 0x99, 0xd4, 0x91,
	0x75, 0x6f, 0x55, 0x3a, 0xcb, 0x8b, 0xf9, 0x43, 0xba, 0x95, 0xed, 0x90, 0xea, 0xe9, 0x6b, 0x85,
	0xd1, 0xa1, 0x8b, 0x12, 0x67, 0xe9, 0x56, 0x9c, 0xc3, 0x61, 0x59, 0xd1, 0x3a, 0xe7, 0x95, 0xbd,
	0x37, 0x6c, 0x49, 0x76, 0x42, 0x5c, 0xe8, 0x1b, 0xbf, 0x17, 0x05, 0x66, 0xde, 0xf8, 0xe1, 0x6c,
	0x91, 0x16, 0x73, 0x92, 0xdd, 0xdd, 0xf0, 0xad, 0xc2, 0x48, 0x7c, 0x4d, 0x7c, 0x3d, 0x53, 0x95,
	0x51, 0xe1, 0x24, 0xc4, 0x9a, 0xa1, 0xfe, 0x89, 0x60, 0x19, 0xcd, 0x5d, 0xe3, 0xb3, 0xbe, 0x37,
	0x4d, 0xc2, 0x2f, 0x8d, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xe9, 0xcd, 0x7b, 0xda, 0xc0, 0x01,
	0x00, 0x00,
}
